### ISSUE TITLE
External and native libraries

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#1]
One of the TotalCross developers most requested features is the possibility of using native and external libraries within their applications. This functionality is extremely important for several reasons, among them, being able to use serial ports like RS232, access peripherals, and perform hardware analysis. It is our number one priority.

To implement this, we divided it into two macro activities: 
* Create a new method based on the runtime.exec of java; 
* Improve **TCNI** for community use;

**Please, feel free to contribute with your questions or suggestions!**

**Comment by ricardobna** [comment]
I am working on Runtime.exec, so far I've done FileInputStream on C side, just need to figure out a way to properly read the stream to run some tests.

**Comment by ricardobna** [comment]
I got to read a file on C and stream it to a Process on Java with FIleInputStream. This allowed me to run some tests with reading a file and printing its contents with `println`.

**Comment by ricardobna** [comment]
Finished the Output and Error streams bindings, still need to run some tests on linux with exec.

**Comment by ricardobna** [comment]
Finished testing for linux Runtime.exec should be working on feature/runtime-exec branch. As a side note, passing a file won't change anything as of now, as it's not yet implemented, we will be looking to implement this part at a latter stage of development of this feature.

**Comment by ricardobna** [comment]
Just finished the Java interface and the File path, now you can do exec("command") and it should work just fine.

**Comment by ricardobna** [comment]
Added destroy, exitValue and waitFor methods today, also added some exceptions to these methods, all changes are on feature/runtime-exec

**Comment by ricardobna** [comment]
Finished Runtime.exec, the calls are the same as Java's and the changes can be found on feature/runtime-exec branch or it's pull request #21.

**Comment by pattrickx** [comment]
Runtime.exec does not terminate processes when the application window is closed.
