### ISSUE TITLE
Improve error warnings in the VSCode plugin and CLI;

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#10]
We have already had some reports of people using the plugin and finding errors that they did not warn on the console or the warning in the log does not make it clear what the problem is.

The most current is from a user who had no root space so when he was using the plugin to deploy it he did not download the SDK. With that nothing happened, nor did it warn of an error.

**Comment by acmlira** [comment]
Makes more sense moves this issue to VS Plugin and CLI repos :sweat_smile:
