### ISSUE TITLE
Virtual keyboard for Linux x86-64 and Linux ARM is not working 

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#12]
Even after adding `Settings.virtualKeyboard = true` and `Settings.enablevirtualKeyboard = true` to the app's builder, it doesn't work, neither in the **simulators** neither on the **board**.

**Comment by acmlira** [comment]
I've checked, this bug is occurring on Linux ARM and Linux x86-64 platforms, therefore this issue was renamed and retagged

**Comment by acmlira** [comment]
Hi everyone!

The bug was maybe solved, checkout branch `bugfix/virtual-keyboard-linux`. The changes have been tested for Linux x86-64 (Ubuntu 18.04), you just need to change the application's static block:

```java
...

static {
    Settings.virtualKeyboard = true;
}

...
```

**Comment by ItaloYeltsin** [comment]
I think should come `true` by default for embedded systems.

**Comment by acmlira** [comment]
Makes sense, the default window size on SDL initialization is `FULLSCREEN`, something about UX must say that it is better :robot:

**Comment by acmlira** [comment]
Hey @VaneskaSousa we are waiting for some feedback to close this issue. Here are also instructions on how to build the SDK if you need :sweat_smile:

**Comment by gb88** [comment]
I try the fix and is working on toradex iMX6ULL, i follow the [instruction](https://github.com/TotalCross/totalcross/wiki/How-to-build-TotalCross-SDK) to compile the SDK and i copied the file in the VM folder in my packed file that goes to the boad.

**Comment by ItaloYeltsin** [comment]
Two things we have to change here. 
 1 - By default, totalcross must use virtualKeyboard by defaults it doesnt detect a phisical keyboard;
2 - The ripple effect on the virtual keyboard can be a performance issue for devices using iMX6ULL, maybe we should provide a way to disable it!

**Comment by ItaloYeltsin** [comment]
It's also important to highlight that even if the platform detects a phisical keyboard, we must provide a way to our users to allow the use of our virtual keyboard.

**Comment by acmlira** [comment]
I think the first point had a simple solution but the second ... :anguished:

**Comment by acmlira** [comment]
See #40
