### ISSUE TITLE
Buggy performance on Edit component

### ISSUE THREAD

**Issue by ItaloYeltsin** [TotalCross/totalcross#123]
## Describe the bug
Testing TCSample on my Raspberry Pi 4, CPU usage goes high above the sky and the aplication gets stuck.

## To Reproduce
1. Open the Side menu
2. Goto UI > Edit.
3. Write something on some Edits
4. Go to other Screen
5. Go back to the Edit Screen and fill again some Edits

By 3 to 5 twice on my Raspberry, CPU goes high to 100% usage.
 
![image](https://user-images.githubusercontent.com/4422007/90662492-ce85e880-e21e-11ea-912c-6fd37af89716.png)

# Expected behavior
Fill the Edit components without such an increament of CPU Usage

## Devices:
Please complete the following information:
 - Device: Raspberry Pi 4
 - OS: Linux Raspberry OS
 - TotalCross Version: 6.1.0

**Comment by brunoamuniz** [comment]
@teras @VicMisael any updates?! =)

**Comment by teras** [comment]
There is already a fix for this issue. It still needs some fine tuning, because as is it might have a memory leak, and I need to verify and strengthen the memory consumption before asking for pull request.

**Comment by brunoamuniz** [comment]
@VicMisael what is the status of this issue? =)

**Comment by VicMisael** [comment]
@brunoamuniz  It's fixed by the keyboard fixes made before, so i'll be closing it
