### ISSUE TITLE
Multiple launcher files with essentially same code

### ISSUE THREAD

**Issue by otavio** [TotalCross/totalcross#13]
Multiple launcher applications are available however they mostly use the same code. It'd be good to rework it so we drop this bunch of duplicated code.

**Comment by ItaloYeltsin** [comment]
Not only multiple launchers but also, we have almost the same Makefile for linux arm and linux x86.

**Comment by otavio** [comment]
Yes, this is not good for reducing duplicated work and maintenance.

**Comment by acmlira** [comment]
I think #30 may solve this issue :smiley:

**Comment by ItaloYeltsin** [comment]
#30 solves it
