### ISSUE TITLE
Enable use of PWM, analog and Serial ports

### ISSUE THREAD

**Issue by pattrickx** [TotalCross/totalcross#139]
It is essential to use PWM, analog and Serial ports for the development of several projects for embedded devices. TotalCoss already has native methods for using Serial ports, but the process is very laborious and must be improved, in addition to the need to have simple native methods for the use of PWM and analogues.

**Comment by acmlira** [comment]
I agree with you and that should be in our plans, for now we can avoid this problem with `RunTime` and Kernel + user space functions, for example, you can use something like:

```bash
$ cd /sys/class/pwm/pwmchip1/
$ echo 0 > export
```

Select the period of the PWM signal. Value is in nanoseconds.

```bash
echo 1000000 > pwmchip1/pwm0/period
Select the duty cycle. Value is in nanoseconds and must be less than the period.

# echo 500000 > pwm0/duty_cycle
Enable/disable the PWM signal, use 1 or 0 respectively:

# echo 1 > pwm0/enable
Change the polarity of the PWM signal (you can use "normal" or "inversed"). The polarity can only be changed if the PWM is not enabled.

# echo "normal" > pwm0/polarity
