### ISSUE TITLE
Launcher files do not state correct license

### ISSUE THREAD

**Issue by otavio** [TotalCross/totalcross#14]
The project state it is LGPL-2.1 however files say otherwise:

https://github.com/TotalCross/totalcross/blob/develop/TotalCrossVM/src/launchers/linux/Launcher.c#L1-L10

**Comment by acmlira** [comment]
Great feedback, let's work on it to launch a `hotfix` :sweat_smile:

**Comment by otavio** [comment]
I did not review other files but it'd be good to go over all files.

Also, it'd be good to use a formal header, such as:

https://github.com/UpdateHub/updatehub/blob/master/updatehub/src/lib.rs#L1-L3

**Comment by acmlira** [comment]
Hello @otavio, can you give us more information about this format?

**Comment by otavio** [comment]
What is missing? I added the two links with the issue and with the way we do. Check the both links.

**Comment by otavio** [comment]
Yes; your license compliance is likely very broken as it is easy to get wrong and messy. I'd convert your header files (of your source files) and not touch 3rd party libraries.

**Comment by acmlira** [comment]
Hey @otavio I think #23 and #24 may solve your issue. Let's wait a few more days to close, if there are any additional questions
