### ISSUE TITLE
 Bad behavior in the click effect of the button

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#140]
## Describe the bug
When I click in the button the efect (white color) don't fades away (like in the screenshot)

## To Reproduce

<pre>
Button start = new Button("Start", Button.BORDER_OUTLINED);
start.setBackForeColors(Colors.SECUNDARY, Colors.P_FONT);
add(start, CENTER, AFTER + Constants.DP_100);
</pre>

## Screenshots or videos
![](https://i.imgur.com/mUTGSYX.png)

## Devices:
Please complete the following information:
 - Device: windows and moto G7 play
 - OS: android and windows
 - OS Version: 10 and 10 
 - TotalCross Version: 6.0.4 and 6.1.0

## Additional context
I'm using TotalCross to build the breakout game for my project in university so will be nice if in 10/4 I have a new version with everything ok 😄 

And I don't want to remove the click effect because it looks really weird and doesn't look like a clickable component

Thanks!

**Comment by ricardobna** [comment]
Is there anything running on the background? This doesn't looki like a Button bug, at least not from the code you provided.

**Comment by VaneskaSousa** [comment]
@ricardobna hmm, I just put the `swap(InitialScreen.java);` on my `GameEngine. 
My code https://github.com/VaneskaSousa/breakout-tc

**Comment by teras** [comment]
Is this related to #184 ? 
There's some problem with animations and events for Button

**Comment by VaneskaSousa** [comment]
Yes, its the same i guess. And I test it on 6.1.1 and dont have problem so I will close the issue 😄
