### ISSUE TITLE
Upgrade the Ubuntu image used with Docker

### ISSUE THREAD

**Issue by flsobral** [TotalCross/totalcross#141]
The EOL for Xenial is 2021-04. The end of life will happen in about 8 months. After that, only security fixes.

Shouldn't be used a version with an extended life cycle? Like, Beaver or Fossa?

_Originally posted by @jeffque in https://github.com/TotalCross/totalcross/pull/138#r484981924_

**Comment by flsobral** [comment]
We use Xenial as base image to ensure libc compatibility with a particular Angstrom distro.
I'm not sure the EOL matters for us in this case.

**Comment by jeffque** [comment]
So, I have some concern about this since I've tried something with the Xerial/sqlite-jdbc repo and the Travis-CI build got wrong because the image described in the build has reached EOL. I have no idea for how long an unsupported image will persist on DockerHub

**Comment by acmlira** [comment]
I don't think this is an issue at the moment, we have no warning about it even using the `:latest` version

**Comment by flsobral** [comment]
We'll wait until this becomes a problem, at least some warning about the EOL or deprecated status of the version.
