### ISSUE TITLE
License file inside the SDK pointing to LGPL v.3

### ISSUE THREAD

**Issue by brunoamuniz** [TotalCross/totalcross#143]
Hey, the license file inside the last SDK in my machine is pointing to LGPL v.3

THIS LICENSE APPLIES TO THE SDK BUT NOT FOR THE VIRTUAL MACHINES
   GNU LESSER GENERAL PUBLIC LICENSE
       Version 3, 29 June 2007

TotalCross is LGPL v.2.1, could you change that? =)

**Comment by acmlira** [comment]
Very critical, we must **launch a new version urgently**

**Comment by acmlira** [comment]
Was fixed in #145.
