### ISSUE TITLE
Release 6.1.1 version

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#156]
# Release 6.1.1 version

I realized that it's been a while since the release of 6.1.0 but it miss finishing the issues bellow:

- [x] AnonymousDataUser #148 ;
- [x] otalCross simulator won't run on Windows 10 #153;
- [x] Fixes: KnowCode Slider 

🚀 So doing that I believe that we already have enough for a new version. 🚀 

Therefore, for the release we need and, for now, those responsible for each item:

- [x] Peer Review: Completed during pull request reviews
- [x] Integration tests: the whole time is involved (Those who perform tests must fill out this [form](https://forms.gle/bH1uAf8oWuojCGF26).)
- [x] Generate the SDK:
- [x] Upload in Artifactory: 
- [x] Upload in S3 (Amazon Server):
- [x] Test the SDK again
- [x] Write the changelog: 
- [x] Update JAVADOCS
- [x] Update the SDK download links in enterprise area and documentation:  
- [x] Update samples in TotalCross repositories for 6.1.1

So, that is it. 

### Feel free to help us to test and improve our SDK ❗ 🙏

**Comment by flsobral** [comment]
Merging the PR #148 wrongfully closed this issue. =/

**Comment by flsobral** [comment]
Tagged and released here on github
