### ISSUE TITLE
Border is not set using setBorderColor and setBorderStyle

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#176]
## Issue Title
The border is not set

## Describe the bug
The border is not visible when set

## To Reproduce
Just execute the following code:
        Container ct=new Container();
       
        ct.setBorderStyle(Container.BORDER_SIMPLE);
        ct.borderColor=Color.BLUE;
        ct.setBackColor(Color.RED);
        add(ct, CENTER, CENTER,70,70);

## Expected behavior
A blue border should be visible

## Screenshots or videos
![image](https://user-images.githubusercontent.com/29692098/97734645-332fb000-1ab8-11eb-8dca-7018a5441357.png)

## Devices:
Please complete the following information:

 - OS:Windows 
 - OS Version: 10 2004
 - TotalCross Version: 6.1.1(Simulator)

**Comment by ricardobna** [comment]
Hey @VicMisael, can you check if this bug still happens on branch bugfix/container-border?

**Comment by VicMisael** [comment]
![image](https://user-images.githubusercontent.com/29692098/98811837-399b2180-2400-11eb-902c-eacbd6cbd5eb.png)
