### ISSUE TITLE
Messagebox Title is not shown using anything other than MATERIAL_UI

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#177]
## Issue Title
Messagebox Title is not shown using anything other than MATERIAL_UI

## Describe the bug
A clear and concise description of what the bug is and the actual behavior.

## To Reproduce
Execute the following line of code with the UI style set to anything other than MATERIAL_UI
```
   setUIStyle(Settings.ANDROID_UI);
   new MessageBox("Titulo","Teste").popup();
```
## Expected behavior
On every other Ui style, the MessageBox Title should be shown 

## Screenshots or videos
![image](https://user-images.githubusercontent.com/29692098/97737139-645daf80-1abb-11eb-825b-1f0be1e207fc.png)

## Devices:
Please complete the following information:
 - Device:PC
 - OS:Windows
 - OS Version: 10 2004
 - TotalCross Version: 6.1.1

**Comment by brunoamuniz** [comment]
@ricardobna any updates on this? =)

**Comment by ricardobna** [comment]
Tried one solution but it didn't work, I'm trying another one now, will update as soon as I have a result

**Comment by ricardobna** [comment]
Putting this issue on hold while I work on #190, as soon as I have something new for this bug I'll report here.

**Comment by teras** [comment]
The proposed PR should fix this issue

**Comment by teras** [comment]
This issue has been fixed with PR https://github.com/TotalCross/totalcross/pull/241
