### ISSUE TITLE
Allow to use two components as relative

### ISSUE THREAD

**Issue by Iaggoq** [TotalCross/totalcross#18]
In totalcross we can only do a relative with one component, so we can only get a relative position with a x or a y to control the components its better, if we can do a relative positioning with two.
change from: 
add(component,X,Y,W,H,component(relative to x or y));
to
add(component,X,Y,W,H,component(relative x),component(relative y));

**Comment by acmlira** [comment]
This feature already exists, i will move to tag `enhancement`. @ricardobna maybe help you.

**Comment by ricardobna** [comment]
You can use the control you want as a reference for the X and Y, say you have control1, control2 and control3 and you want control3 to be at control1's X and control2's Y you can use `add(control3, control1.getX2(), SAME, PREFERRED, PREFERRED, control2);`.

**Comment by Iaggoq** [comment]
This indeed can solve some like bottom, before, after and top, but how i can do center_of or right_of,

**Comment by ricardobna** [comment]
Can you give me an example of how you want to use center_of and right_of?

**Comment by Iaggoq** [comment]
I would like to use something like this add(control3, control1.getcenterx(), SAME, PREFERRED, PREFERRED, control2);

**Comment by acmlira** [comment]
@Iaggoq or @ricardobna the issue was solved in #89?

**Comment by ricardobna** [comment]
I don't think so, I didn't quite understand the request and forgot to press this issue, can you elaborate a little on this feature @Iaggoq ?

**Comment by Iaggoq** [comment]
The solution you have gave to me its incomplete, some types of positing its not possible to use, like the right_of, center_of and there is some cases which i needed to use theses. @ricardobna

**Comment by ricardobna** [comment]
I think I understood, but still, I fint it odd that the solution I gave you doesn't work, I'll test some solutions and I'll report here if I could make it the way you asked for.

**Comment by ricardobna** [comment]
I looked at Control code to see what can be done to substitute the right_of, center_of and bottom_of, what can be done to replicate this is:
BOTTOM_OF: referencedComponent.getY() + referencedComponent.getHeight() + componentHeight
RIGHT_OF: referencedComponent.getX() + referencedComponent.getWidth() + componentWidth
CENTER_OF: this depends on the axis
- for X axis: referencedComponent.getX() + referencedComponent.getWidth()/2
- for Y axis: referencedComponent.getY() + referencedComponent.getHeight()/2

As you can probably see, for BOTTOM_OF and RIGHT_OF this has a problem, as you need to know the component size beforehand.
