### ISSUE TITLE
Black color is not applied correctly in some elements

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#180]
## Issue Title
Black color is not applied correctly in some elements

## Describe the bug
When a color is set to an side menu element,also tested on an edit, same behavior

## To Reproduce
On an edit:

        Edit ed=new Edit();
        ed.setForeColor(0x0);
        ed.setBackColor(Color.BLACK);
        setBackColor(0x0);
        add(ed,CENTER,CENTER,300,100);

On an SideMenu It's possible to see this behavior using the TCSample code

## Expected behavior
The elements that were painted black, should be black

## Screenshots or videos
The Edit
![image](https://user-images.githubusercontent.com/29692098/97985425-0250c300-1db7-11eb-8f85-c52fe65f05ab.png)
The TCSample(Home color was set red for testing)
![image](https://user-images.githubusercontent.com/29692098/97987605-5c9f5300-1dba-11eb-909e-28048d40f953.png)
Code which sets the side menu items black (UI submenu)
![image](https://user-images.githubusercontent.com/29692098/97988024-0d0d5700-1dbb-11eb-87b3-4158738c324e.png)

## Devices:
Please complete the following information:
 - Device: Simulator
 - OS: Windows
 - OS Version: 10 2004
 - TotalCross Version: 6.1.1

**Comment by ricardobna** [comment]
Just checked this, it is done that way on purpose to look better, but it limits customization, I'm addressing this by allowing the user to use our aproach or use whatever they want. This only happens on Edit and SideMenuContainer or was there any other component which this behavior occured?

**Comment by VicMisael** [comment]
Only on side menu and edits

**Comment by ricardobna** [comment]
Hey @VicMisael, can you check if this bug still happens on branch bugfix/edit-sidemenu-color?

**Comment by VicMisael** [comment]
Yes i can, soon i'll be showing the results

**Comment by VicMisael** [comment]
It is working on the simulator no issues, testing on others platforms now

**Comment by VicMisael** [comment]
Tested on other platforms, it's working fine, but these additions to the cold should be added to the documentation right?

**Comment by brunoamuniz** [comment]
hey @VicMisael who are u asking for? Please always tag someone if you need an answer =)
