### ISSUE TITLE
Push button group is laggy on Android

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#181]
## Issue Title
Push button group is laggy on Android

## Describe the bug
Push button is laggy on Android

## To Reproduce
Use the following code to generate the pushbutton

` add(new PushButtonGroup(new String[]{"Button1","Button2","Button3"},false,-1,-1,4,0,false,PushButtonGroup.NORMAL), CENTER, CENTER);`

## Expected behavior

The buttons should not be laggy

## Screenshots or videos

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29692098/97997595-e275cb00-1dc7-11eb-89dd-f460a1bfa591.gif)

## Devices:
Please complete the following information:
 - Device:Lenovo Vibe K5
 - OS: Android 
 - OS Version: 6.0.1
 - TotalCross Version: 6.1.1

## Additional Information
May be related to issue #173 and #124

**Comment by brunoamuniz** [comment]
@VicMisael @teras guys are you working on this? Is it the same issue? If so, could u move to the right lane on the board =)

**Comment by teras** [comment]
I haven't test it, but it sounds similar. Probably when we fixed the other issue, this will be fixed too.
