### ISSUE TITLE
Onscreen keyboard registers double key press

### ISSUE THREAD

**Issue by teras** [TotalCross/totalcross#184]
## Describe the bug
When pressed the onscreen keyboard, sometimes the button produces two characters instead of one.

## To Reproduce
Launch keyboard, press some buttons, press the same buttons again, then the problem will appear.

## Expected behavior
To register only one key instead of two

## Devices:
Please complete the following information:
 - Device: Emulator
 - OS: All OS
 - OS Version: ...
 - TotalCross Version: master branch

**Comment by mando0192** [comment]
Hello, when I launch the keyboard, it register a double input. At first it was some keys but later on more keys had the same behaviour

**Comment by brunoamuniz** [comment]
@mando0192 It's happening only with number or with letters, too? Could you provide a short video about it?

**Comment by brunoamuniz** [comment]
@teras @VicMisael any updates? Probably we need to check all the keyboards, including letters, numbers, and symbols

**Comment by teras** [comment]
This issue should be solved already.
I propose, when we close issue #193 , please @VicMisael have a second check on all keyboards and see if all keyboard problems are gone.

Just a note: the problem was never with the keyboard itself, but rather the button bugs were more obvious then.

**Comment by VicMisael** [comment]
I had a look at the keyboards, that double click issue is not present, I will be closing this issue
