### ISSUE TITLE
JAVA in full screen on Raspberry

### ISSUE THREAD

**Issue by teras** [TotalCross/totalcross#185]
## Is your feature request related to a problem? Please describe.
Is it possible to use the Graphic API to run on a Raspberry PI directly with Java, without using the VM? The application should work on Full Screen.

How can be done?

**Comment by pedropaulolyra** [comment]
Tested on Desktop and Raspberry and both is opening in Fullscreen mode, but on Raspberry did not load the components. Only the background was shown and this exception came up.

![image](https://user-images.githubusercontent.com/48485441/98578132-b19c0700-229b-11eb-891e-cb47499b60da.png)

**Comment by brunoamuniz** [comment]
Ask him what is the version of JAVA he is using and the vendor

**Comment by brunoamuniz** [comment]
@VicMisael could you simulate that and pass the results to @teras ?

**Comment by pedropaulolyra** [comment]
He is using the Openjdk 11.0.9. 

![image](https://user-images.githubusercontent.com/48485441/98670089-ee660d80-2330-11eb-98ba-d70ee64dec90.png)

**Comment by VicMisael** [comment]
I was testing with @teras , Looks like this issue it's not related to the full screen, just to the resolution, so I'll be closing it, and opening a new one

**Comment by VicMisael** [comment]
A workaround to this issue is to add this dependency to pom.xml
<dependency>
    <groupId>net.coobird</groupId>
    <artifactId>thumbnailator</artifactId>
    <version>0.4.8</version>
</dependency>
