### ISSUE TITLE
Label bold not working

### ISSUE THREAD

**Issue by Iaggoq** [TotalCross/totalcross#189]
## Issue Title
Totalcross's Label bold not working

## Describe the bug
Using totalcross code to make the text bold and not using is the same
![image](https://user-images.githubusercontent.com/29692098/98547502-0bd6a100-2277-11eb-896a-7d80d32d894f.png)

## To Reproduce
```
		Label label = new Label("bold");
		label.setFont(label.getFont().asBold());
		container.add(label,CENTER,TOP,PREFERRED,PREFERRED);
		Label label2 = new Label("not bold");
		container.add(label2,SAME,AFTER,PREFERRED,PREFERRED);
```

## Expected behavior
label become bold

## Devices:
Please complete the following information:
 - Device: Simulator
 - OS: Windows
 - OS Version:  10 2004
 - TotalCross Version: 6.1.1

**Comment by brunoamuniz** [comment]
@ricardobna What do you think about deprecating the "bold" method/variable and add a sample code of how to do it?

**Comment by teras** [comment]
System font does not support bold version. In order to protect the developer of this mistake, an exception will be thrown to indicate that this is not possible

**Comment by teras** [comment]
This issue has been addressed with pull request 
https://github.com/TotalCross/totalcross/pull/252

System font doesn't support bold version. So remove all references to default to a bold version of system font and create an error if the user does this by mistake.
