### ISSUE TITLE
Awful performance + CPU usage skyrocketing using a Numeric Keyboard

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#193]
## Issue Title
Slow performance using number keyboard

## Describe the bug
When the virtual number keyboard is open, and some number is typed,it's very slow

## To Reproduce
set the constructor this way
```
        Settings.virtualKeyboard=true;
        setUIStyle(Settings.MATERIAL_UI);
```
after this, add the edit component with a numeric keyboard
```
        Edit ed2=new Edit();
        ed2.setKeyboard(Edit.KBD_NUMERIC);
        add(ed2,CENTER,CENTER );
```
try to use the component, you should see the issue 

## Expected behavior
The Cpu usage should be not as high, and also, the keyboard should work with an acceptable performance
## Screenshots or videos

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/29692098/98575500-0a69a080-2298-11eb-9bd9-dc362911aec0.gif)

CPU usage:
![image](https://user-images.githubusercontent.com/29692098/98575749-54eb1d00-2298-11eb-9ced-d68540740199.png)

## Devices:
Please complete the following information:
 - Device: Simulator,and Raspberry pi
 - OS: Linux Raspbian
 - TotalCross Version: 6.1.1

## Additional context
Related to issue #184 (Tested with that commit )https://github.com/TotalCross/totalcross/commit/398e718a4088e4c95b625f94a20a473b9fb67dc8

**Comment by teras** [comment]
Have you checked this issue with the fix from #184?

**Comment by VicMisael** [comment]
Yes,I should note this on the issue

**Comment by VicMisael** [comment]
Related to #181
