### ISSUE TITLE
Update Skia to m87

### ISSUE THREAD

**Issue by flsobral** [TotalCross/totalcross#196]
TotalCross is using Skia m71, which is almost 2 years old?
Updating Skia is important to keep up with the latest fixes and upgrades.

**Comment by flsobral** [comment]
Skia m87 successfully built for Linux, MacOS and Android.
TotalCross build updated from C++11 to C++14 to meet Skia requirements.
Fixed TotalCross' drawing text primitives - Skia had some breaking changes.

Current state:
1 - Material Icons are not being displayed on any platform, will check if this is a regression or a bug that wasn't noticed before;
2 - Performance in Linux desktop is not great, will compare with previous version to measure the actual difference;
3 - Text is not correctly displayed on Linux desktop: text is not centered and sometimes truncated;

**Comment by brunoamuniz** [comment]
@flsobral any update on this? =)

**Comment by acmlira** [comment]
Skia has been successfully built for all platforms as far as I know. I also know that Farshid and I were working on some optimizations. @flsobral can give us more information.

**Comment by flsobral** [comment]
Built for Android, iOS, MacOSX, Linux x86_64 and arm64.
Working on build for armv7.

**Comment by Farshid-Monhaseri** [comment]
Building libtcvm was done with Skia m87 ... we are on testing it and maybe tweak some of the configs for each platform.

**Comment by acmlira** [comment]
We are very close to closing the issue, now we are organizing the commits and doing the final tests before integrating.

**Comment by teras** [comment]
Is this issue fixed? Should we close this issue?

**Comment by acmlira** [comment]
#224 was merged i think we can close this one.
