### ISSUE TITLE
The simulator crashes after setting a resolution above a threshold

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#197]
## Issue Title
The simulator crashes at some resolutions above a threshold

## Describe the bug
When setting the simulator resolution to 1203x653 it crashes, but when its 1202x652 it runs fine

## To Reproduce
download TCSample and set the TCSampleApplication.java like this

```
package totalcross.sample;

import totalcross.TotalCrossApplication;
import totalcross.sample.main.TCSample;

public class TCSampleApplication {
	public static void main(String[] args) {
	    TotalCrossApplication.run(
	        TCSample.class, "/r", "<PLACE YOUR KEY>","/scr","1203x653");
	  }
}
```

## Expected behavior
The simulator should at any resolution without any issue

## Screenshots or videos
the screen
![image](https://user-images.githubusercontent.com/29692098/98712362-f8a1ff00-2364-11eb-8f86-f4b9f1b60ac4.png)
the exception that it's thrown
![image](https://user-images.githubusercontent.com/29692098/98712504-271fda00-2365-11eb-84a7-f7671b99c8b2.png)

## Devices:
Please complete the following information:
- Device: Simulator
- OS:Windows
- JDK:Zulu OpenJDK11
## Additional information
Related to the issue #185 
Using the last commit of Totalcross SDK and TCSample
Tcsample: https://github.com/TotalCross/tc-sample

**Comment by VicMisael** [comment]
Adding this dependency to the TCSample pom.xml fixes the issue
```
<dependency>
    <groupId>net.coobird</groupId>
    <artifactId>thumbnailator</artifactId>
    <version>0.4.8</version>
</dependency>

```

**Comment by teras** [comment]
Since the crash is due to missing dependency, and adding this dependency fixes the crash, this issue will be closed.
