### ISSUE TITLE
Simulator resolution doesn't change the screen size past some resolution

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#198]
## Issue Title
Simulator resolution doesn't change the screen size past some resolution.

## Describe the bug
Setting a resolution at the simulator, if this resolution is great enough, the screensize doesn't grow bigger, it seems to be relative to the resolution of the host system,as seem in the screenshots below

## To Reproduce
Just set the main resolution of the host machine or greater
```
TotalCrossApplication.run(
	        TCSample.class, "/r", "<PLACE YOUR KEY>", "/scr", "iphone");
```

## Expected behavior
The screen resolution should scale with set resolution at the code above

## Screenshots or videos
all screenshots were taken using a 1366x768 screen

Using 1366x768
```
TotalCrossApplication.run(
	        TCSample.class, "/r", "<PLACE YOUR KEY>", "/scr", "1366x768");
```
![image](https://user-images.githubusercontent.com/29692098/98949228-31adb100-24d6-11eb-9c45-c907c7f18add.png)

Using 1080p
```
TotalCrossApplication.run(
	        TCSample.class, "/r", "<PLACE YOUR KEY>", "/scr", "1920x1080");
```

![image](https://user-images.githubusercontent.com/29692098/98949295-47bb7180-24d6-11eb-9888-717990b1fdd9.png)

Using 1440p

```
TotalCrossApplication.run(
	        TCSample.class, "/r", "<PLACE YOUR KEY>", "/scr", "2560x1440");
```

![image](https://user-images.githubusercontent.com/29692098/98949335-56a22400-24d6-11eb-9dcf-b514a9a44cb8.png)

## Devices:
-Device:Simulator
-JDK:Zulu

## Additional Context
Related to #197

**Comment by VicMisael** [comment]
It's important to note that, this issue is present running with or without fullscreen mode

**Comment by teras** [comment]
When we provide the parameter `/scale 1` it works as expected.
This is due to some optimizations for bigger screens, not to exceed a specific ratio, and to scale instead.
Needs some more feedback whether this should be the expected default behavior.

**Comment by VicMisael** [comment]
This issue is fixed by using ("/scr","1920x1080","/scale 1") @brunoamuniz  thinks that it should be closed, so I'll be closing it
