### ISSUE TITLE
Organize TCVM, TC API Java and Litebase in different repositories on github

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#2]
From version 6 [TotalCross SDK is open source](https://github.com/TotalCross/totalcross/). Our goal is to make contributing the simplest, facilitating the understanding of what makes up the TC SDK.

But we have some difficulties because if we separate the repositories will cause **cyclic dependencies** between them.

Please, feel free to contribute with your help and questions!

**Comment by ItaloYeltsin** [comment]
Tasks related to this feature:

- [ ] Build Windows 32-bit/ARMV4 on gcloud

- [ ] Build linux arm

- [ ] Build linux

- [ ] Build Android

- [ ] Pack into TotalCross SDK

**Comment by jeffque** [comment]
There is little to no use of doing it in different repositories.

Have you eve heard of the"monorepo" concept? It may be helpful to understanding how to get it contributable

**Comment by acmlira** [comment]
I think the scope is still defined or this is no longer a issue. Hey @ItaloYeltsin what do you think about it?

**Comment by ItaloYeltsin** [comment]
We had a little discussion on Telegram, but we have not decided yet. Anyways, litebase must be removed. For now, I think we must at least rename the folders from **TotalCrossSDK** and **TotalCrossVM** to **sdk** and **vm**.

**Comment by flsobral** [comment]
Splitting the SDK and the VM into separate repositories makes no sense, not to mention the extra trouble keeping both versions in sync.

Moving Litebase to its own repository does make sense and it's something I'd like to do, but it's not something we are going to do for the time being.
