### ISSUE TITLE
Changing the UIStyle causes slower performance on Win32 and Linux_ARM

### ISSUE THREAD

**Issue by VicMisael** [TotalCross/totalcross#217]
## Issue Title
Changing the UIStyle causes slower performance on Win32

## Describe the bug
Changing The UIStyle from Material_ui to android_ui causes slower performance when compiled to win32

## To Reproduce
Pull this repository
https://github.com/TotalCross/TcTest
Set UI_Style to MATERIAL_UI
```
setUIStyle(Settings.MATERIAL_UI);
```
package for windows

test and see how much time it takes,then do all these steps again  but with UI_style set to android
```
setUIStyle(Settings.ANDROID_UI);
```
## Expected behavior
The test should take the same time on both

## Screenshots or videos
![image](https://user-images.githubusercontent.com/29692098/100367585-3186d880-2fe1-11eb-99c1-edf6f72710cb.png)

## Devices:
Please complete the following information:
 - Device: PC
 - OS: Windows 
 - OS Version: 10 x64
 - TotalCross Version: Master(Also on 6.1.1)

**Comment by brunoamuniz** [comment]
Did you try on linux arm and android, too? What was the results?

**Comment by VicMisael** [comment]
I've tried on Linux arm, here are the results
![image](https://user-images.githubusercontent.com/29692098/100448777-98fc6100-3091-11eb-9dbf-97706c3734a8.png)
About 3 minutes
Using android, the application ran for more than 10 minutes and had no results

**Comment by VicMisael** [comment]
Should we deprecated ANDROID_UI? @flsobral , @teras , @ricardobna

**Comment by teras** [comment]
Because it's not modern any more?
We can show an error message that "this UI is deprecated" if we want something like this.

**Comment by nmarquesin** [comment]
@teras what do you think of deprecating all UI versions but flat and material, for version 7?

**Comment by nmarquesin** [comment]
The team agreed that we are going to deprecate all UIs with the exception of flat and material on version 7. @ricardobna, could you please do this task and close the issue when you have done it? :)

**Comment by VicMisael** [comment]
Using the nightly version seems to narrow the gap between material and Android ui styles

**Comment by teras** [comment]
This issue has been fixed with the PR from https://github.com/TotalCross/totalcross/issues/193

The issue will be closed.
Please feel free to re-open the issue if the problem still persists.
