### ISSUE TITLE
TC445 can't deploy .apk to Google Play Store

### ISSUE THREAD

**Issue by alexm7** [TotalCross/totalcross#223]
## Issue Title
TC445 can't deploy .apk to Google Play Store.  API level needs to be updated to 20.

## Describe the bug
When you upload the .apk file it says:
"Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29."

## To Reproduce

1. Run tc.deploy to create .apk file
2. Upload to google play
3. Error message is displayed:
"Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29."

## Expected behavior
Google play store accepts .apk file for deployment

## Screenshots or videos
![image](https://user-images.githubusercontent.com/5192366/101295747-8b5f7d80-37ed-11eb-9072-f3c7280e4fc5.png)

## Devices:
Please complete the following information:
 - Device: Android
 - OS: Android
 - OS Version: any
 - TotalCross Version: 445

**Comment by brunoamuniz** [comment]
@VicMisael can u test this? =)

**Comment by VicMisael** [comment]
@flsobral What android Sdk version are we using?

**Comment by VicMisael** [comment]
[totalcross-android-29 (3).zip](https://github.com/TotalCross/totalcross/files/5797956/totalcross-android-29.3.zip)
Just overwrite the files at your local totalcross repository

**Comment by alexm7** [comment]
Hi Vic,
I'm currently using TC4.4.5.  The TotalCross.apk file is 8.2MB in size.
The file you sent has the TotalCross.apk file as 7.7MB in size.

Are you sure this is correct that the file size has reduced by this much just because of this update.
Please confirm.
Thanks
Alex.

**Comment by VicMisael** [comment]
Yes, Just because it's better optimized, try it please, and give us the results

**Comment by alexm7** [comment]
I was able to create a new release and deploy in the Google Play Store.  So this is working now.  

Thanks.

**Comment by VicMisael** [comment]
Ok, so, I'll be closing this issue, thank you for your patience
