### ISSUE TITLE
CI is not triggering for forked PRs

### ISSUE THREAD

**Issue by acmlira** [TotalCross/totalcross#234]
The repository forks workflow is much more organized and less likely to generate large errors. This issue does not want to change the development paradigm, but only to allow us to work like this and mainly to 

<div align="center">

### allow external contributions

</div>

yes, it is impossible to be an external contributor! To solve this problem, just an **administrator of the organization** changes the permission as follows:

![forked-repo-issue](https://user-images.githubusercontent.com/30937401/102420989-1b69a800-3fe2-11eb-908d-46ef5f07cee2.gif)

**Comment by brunoamuniz** [comment]
Hey @acmlira, just added the permission =P

Try it now, try it!!!

**Comment by acmlira** [comment]
Working!
