### ISSUE TITLE
CI is not providing all necessary artifacts for release

### ISSUE THREAD

**Issue by acmlira** [TotalCross/totalcross#235]
For all artifacts to reach the end user in the correct way, the build must also have the following .jar by-products:
- totalcross-sdk-x.x.x-javadoc.jar
- totalcross-sdk-x.x.x-sources.jar

We cannot release new versions without them, so we are still a long way from a CD since they are still obtained manually.

**Comment by VicMisael** [comment]
Are these file generated when compiling the SDK ?

**Comment by acmlira** [comment]
Yes, inside `TotalCrossSDK/build`
