### ISSUE TITLE
Build inside docker container for arm64 is broken

### ISSUE THREAD

**Issue by acmlira** [TotalCross/totalcross#236]
The latest build **inside docker container** for arm64 with clang and c++ 17 returned:

```log
#14 322.7 In file included from /sources/src/nm/ui/android/skia.cpp:37:
#14 322.7 In file included from /sources/modules/skia/include/core/SkPathEffect.h:12:
#14 322.7 /sources/modules/skia/include/core/SkPath.h:1593:20: error: chosen constructor is explicit in copy-initialization
#14 322.7             return {verb, fPoints + backset, fWeights};
#14 322.7                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#14 322.7 /usr/bin/../lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/tuple:479:19: note: constructor declared here
#14 322.7         constexpr tuple(_UElements&&... __elements)
#14 322.7                   ^
#14 322.7 1 error generated.
#14 322.7 ninja: build stopped: subcommand failed.
#14 ERROR: executor failed running [/bin/sh -c cmake /sources -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DPNG_ARM_NEON_OPT=0 -G Ninja && ninja]: exit code: 1
------
 > [build 10/10] RUN cmake /sources -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DPNG_ARM_NEON_OPT=0 -G Ninja && ninja:
```

this error needs to be investigated further. All scripts and build references were made to the files in the docker subfolder. The branch in which this is seen is the `revert/5e1166b6d7c0510290ca4c96483296f57ced1ffe` (bad named by me).

**Comment by teras** [comment]
What is "tuple" ?

**Comment by acmlira** [comment]
See this https://en.cppreference.com/w/cpp/utility/tuple

**Comment by teras** [comment]
I can see the ellipsis inside a tuple.. this might be the source of the problem. It definitely is a compiler incompatibility with the OS....

**Comment by acmlira** [comment]
"Fixed" it is not a real issue as you can see in the actions menu.

**Comment by acmlira** [comment]
Sometimes the containers cannot be built, because the download of a dependency, for some reason, fails. My suggestion is to freeze (and version) the good containers on DockerHub.
