### ISSUE TITLE
Getting started Java 8 install command does not work on Mac OS X 

### ISSUE THREAD

**Issue by ItaloYeltsin** [TotalCross/totalcross#25]
The command shown in our [getting started](https://learn.totalcross.com/documentation/miscelaneous/java-8) does not work anymore.

** current: ** `brew tap AdoptOpenJDK/openjdk && brew install adoptopenjdk-openjdk8`

** the correct one: ** `brew cask install adoptopenjdk/openjdk/adoptopenjdk8`

**Comment by ItaloYeltsin** [comment]
@nmarquesin

**Comment by nmarquesin** [comment]
Thanks, Italo. Documentation is now updated.
