### ISSUE TITLE
TotalCross 515 can't deploy to PlayStore

### ISSUE THREAD

**Issue by marcusrosatekann** [TotalCross/totalcross#254]
## Issue Title
The PlayStore request the API level 29 to publish new apps. TC4-5-6 are 28. This issue is similar to [Issue 223](https://github.com/TotalCross/totalcross/issues/223)

## To Reproduce

1. un tc.deploy to create .apk file
2. Upload to google play
3. Error message is displayed:
4. "Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29."

**Comment by VaneskaSousa** [comment]
Hey guys, did you have any news?

**Comment by VicMisael** [comment]
Yes,we are working on it, but you found some issues while deploying

**Comment by VicMisael** [comment]
[Uploading totalcross5-android-29.zip…]()
This should work, just overwrite the files at your local sdk

**Comment by marcusrosatekann** [comment]
Hi. The zip is redirecting to the issue itself.

**Comment by VicMisael** [comment]
I updated the comment, try it now

**Comment by marcusrosatekann** [comment]
It worked. Thanks.

**Comment by marcusrosatekann** [comment]
Sorry. I didn't do a full test. This is happening when first installing the app.

01-15 10:34:15.652 I/TotalCross(14407): NON-FATAL EXCEPTION
01-15 10:34:15.653 I/TotalCross(14407): java.lang.reflect.InvocationTargetException
01-15 10:34:15.653 I/TotalCross(14407):         at java.lang.reflect.Method.invoke(Native Method)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.appsurv.Settings4A.fillTelephonySettings(Settings4A.java:322)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.appsurv.Settings4A.fillSettings(Settings4A.java:161)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.Launcher4A.nativeOnEvent(Native Method)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.Launcher4A._postEvent(Launcher4A.java:704)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.Launcher4A$2.run(Launcher4A.java:295)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.TCEventThread.privatePumpEvents(TCEventThread.java:70)
01-15 10:34:15.653 I/TotalCross(14407):         at totalcross.TCEventThread.run(TCEventThread.java:44)
01-15 10:34:15.653 I/TotalCross(14407): Caused by: java.lang.SecurityException: getIccSerialNumber: The user 10588 does not meet the requirements to access device identifiers.
01-15 10:34:15.653 I/TotalCross(14407):         at android.os.Parcel.createException(Parcel.java:2071)
01-15 10:34:15.653 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:2039)
01-15 10:34:15.653 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:1987)
01-15 10:34:15.653 I/TotalCross(14407):         at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getIccSerialNumberForSubscriber(IPhoneSubInfo.java:1058)
01-15 10:34:15.653 I/TotalCross(14407):         at android.telephony.TelephonyManager.getSimSerialNumber(TelephonyManager.java:3359)
01-15 10:34:15.653 I/TotalCross(14407):         ... 8 more
01-15 10:34:15.654 I/TotalCross(14407): NON-FATAL EXCEPTION
01-15 10:34:15.654 I/TotalCross(14407): java.lang.reflect.InvocationTargetException
01-15 10:34:15.654 I/TotalCross(14407):         at java.lang.reflect.Method.invoke(Native Method)
01-15 10:34:15.654 I/TotalCross(14407):         at totalcross.appsurv.Settings4A.fillTelephonySettings(Settings4A.java:322)
01-15 10:34:15.654 I/TotalCross(14407):         at totalcross.appsurv.Loader.onRequestPermissionsResult(Loader.java:1329)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8274)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.Activity.dispatchActivityResult(Activity.java:8124)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
01-15 10:34:15.654 I/TotalCross(14407):         at android.os.Handler.dispatchMessage(Handler.java:107)
01-15 10:34:15.654 I/TotalCross(14407):         at android.os.Looper.loop(Looper.java:214)
01-15 10:34:15.654 I/TotalCross(14407):         at android.app.ActivityThread.main(ActivityThread.java:7397)
01-15 10:34:15.654 I/TotalCross(14407):         at java.lang.reflect.Method.invoke(Native Method)
01-15 10:34:15.654 I/TotalCross(14407):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-15 10:34:15.654 I/TotalCross(14407):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
01-15 10:34:15.654 I/TotalCross(14407): Caused by: java.lang.SecurityException: getIccSerialNumber: The user 10588 does not meet the requirements to access device identifiers.
01-15 10:34:15.654 I/TotalCross(14407):         at android.os.Parcel.createException(Parcel.java:2071)
01-15 10:34:15.654 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:2039)
01-15 10:34:15.654 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:1987)
01-15 10:34:15.654 I/TotalCross(14407):         at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getIccSerialNumberForSubscriber(IPhoneSubInfo.java:1058)
01-15 10:34:15.654 I/TotalCross(14407):         at android.telephony.TelephonyManager.getSimSerialNumber(TelephonyManager.java:3359)
01-15 10:34:15.654 I/TotalCross(14407):         ... 17 more
01-15 10:34:15.657 I/TotalCross(14407): NON-FATAL EXCEPTION
01-15 10:34:15.657 I/TotalCross(14407): java.lang.reflect.InvocationTargetException
01-15 10:34:15.657 I/TotalCross(14407):         at java.lang.reflect.Method.invoke(Native Method)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.appsurv.Settings4A.fillTelephonySettings(Settings4A.java:303)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.appsurv.Settings4A.fillSettings(Settings4A.java:161)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.Launcher4A.nativeOnEvent(Native Method)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.Launcher4A._postEvent(Launcher4A.java:704)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.Launcher4A$2.run(Launcher4A.java:295)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.TCEventThread.privatePumpEvents(TCEventThread.java:70)
01-15 10:34:15.657 I/TotalCross(14407):         at totalcross.TCEventThread.run(TCEventThread.java:44)
01-15 10:34:15.657 I/TotalCross(14407): Caused by: java.lang.SecurityException: getDeviceId: The user 10588 does not meet the requirements to access device identifiers.
01-15 10:34:15.657 I/TotalCross(14407):         at android.os.Parcel.createException(Parcel.java:2071)
01-15 10:34:15.657 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:2039)
01-15 10:34:15.657 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:1987)
01-15 10:34:15.657 I/TotalCross(14407):         at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getDeviceIdForPhone(IPhoneSubInfo.java:859)
01-15 10:34:15.657 I/TotalCross(14407):         at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1664)
01-15 10:34:15.657 I/TotalCross(14407):         ... 8 more
01-15 10:34:15.658 I/TotalCross(14407): NON-FATAL EXCEPTION
01-15 10:34:15.658 I/TotalCross(14407): java.lang.reflect.InvocationTargetException
01-15 10:34:15.658 I/TotalCross(14407):         at java.lang.reflect.Method.invoke(Native Method)
01-15 10:34:15.658 I/TotalCross(14407):         at totalcross.appsurv.Settings4A.fillTelephonySettings(Settings4A.java:303)
01-15 10:34:15.658 I/TotalCross(14407):         at totalcross.appsurv.Loader.onRequestPermissionsResult(Loader.java:1329)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8274)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.Activity.dispatchActivityResult(Activity.java:8124)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.ActivityThread.deliverResults(ActivityThread.java:4839)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4887)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
01-15 10:34:15.658 I/TotalCross(14407):         at android.os.Handler.dispatchMessage(Handler.java:107)
01-15 10:34:15.658 I/TotalCross(14407):         at android.os.Looper.loop(Looper.java:214)
01-15 10:34:15.658 I/TotalCross(14407):         at android.app.ActivityThread.main(ActivityThread.java:7397)
01-15 10:34:15.658 I/TotalCross(14407):         at java.lang.reflect.Method.invoke(Native Method)
01-15 10:34:15.658 I/TotalCross(14407):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-15 10:34:15.658 I/TotalCross(14407):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
01-15 10:34:15.658 I/TotalCross(14407): Caused by: java.lang.SecurityException: getDeviceId: The user 10588 does not meet the requirements to access device identifiers.
01-15 10:34:15.658 I/TotalCross(14407):         at android.os.Parcel.createException(Parcel.java:2071)
01-15 10:34:15.658 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:2039)
01-15 10:34:15.658 I/TotalCross(14407):         at android.os.Parcel.readException(Parcel.java:1987)
01-15 10:34:15.658 I/TotalCross(14407):         at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getDeviceIdForPhone(IPhoneSubInfo.java:859)
01-15 10:34:15.658 I/TotalCross(14407):         at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1664)
01-15 10:34:15.658 I/TotalCross(14407):         ... 17 more

**Comment by marcusrosatekann** [comment]
Any news?

**Comment by flsobral** [comment]
Fixed on version 5.2.0, released yesterday.
