### ISSUE TITLE
munmap_chunk(): invalid pointer on IMX8 Nano

### ISSUE THREAD

**Issue by r0n22** [TotalCross/totalcross#259]
## munmap_chunk(): invalid pointer on IMX8 Nano
Trying to run the Arm64 build on IMX8 Nano.  When running Embedded Hello World I am getting the above error

## Describe the bug
Compile the Hello world Sample and copy the latest arm64 Launcher and libtcvm.so to the folder.
Running the code with 
`./Launcher HelloWorld`

I see a quick flash on the screen and the following output:

> Testing video drivers...
> SDL_VIDEODRIVER available: x11 wayland dummy
> SDL_VIDEODRIVER usable   : wayland
> SDL_VIDEODRIVER selected : wayland
> SDL_DisplayMode #0: current display mode is 800x480x67
> SDL_RENDER_DRIVER available: opengl opengles2 software
> SDL_RENDER_DRIVER selected : opengles2
> munmap_chunk(): invalid pointer
> Aborted

## Expected behavior
Hello World application to Run

## Devices:
Please complete the following information:
 - Device: IMX8 Nano
 - OS: Yocto
 - OS Version: Dunfell
 - TotalCross Version: 7.0.0-nightly

**Comment by teras** [comment]
It looks for me that this issue is similar to #263 and #265 . The only difference is it is using opengles2 instead of x11.
And also this happens in ARM64 platform, all of the times.
So it seems like an ARM64 bug.

Please @Farshid-Monhaseri confirm so we can concentrate on this issue.

**Comment by pedropaulolyra** [comment]
Any updates?

**Comment by pedropaulolyra** [comment]
To check if the problem is with Knowcode or not, I'm attaching two samples, the 2i app uses knowcode and the coronachart doen't. 

Could you please try it @VicMisael ?
[install 2i.zip](https://github.com/TotalCross/totalcross/files/5830628/install.2i.zip)
[install coronachart.zip](https://github.com/TotalCross/totalcross/files/5830630/install.coronachart.zip)

**Comment by VicMisael** [comment]
2i doesn't work, a crash related to knowcodeXML, coronachart runs fine,Both of the 64 bits executable don't work since mine is 32 bit

**Comment by VicMisael** [comment]
You can try this libtcvm? It should solve this issue 

[libtcvm.zip](https://github.com/TotalCross/totalcross/files/5843719/libtcvm.zip)
