### ISSUE TITLE
Packaged for win32 failed

### ISSUE THREAD

**Issue by Iaggoq** [TotalCross/totalcross#274]
## Describe the bug
In totalcross 7 win32 package isnt possible getting a error when trying to do packaged

## Devices:
Please complete the following information:
 - System OS (name and version): windows 10
 - TotalCross Version: 7.0.0
 
 
## To Reproduce
create any project and try to do a package with win32

## Screenshots or videos
![image](https://user-images.githubusercontent.com/50816129/104945888-1e1c3c00-5998-11eb-9b53-1ec8c61bb537.png)

**Comment by brunoamuniz** [comment]
iOS didn't work either

java.io.FileNotFoundException: Source '/Users/brunomuniz/Library/Application Support/TotalCross/7.0.0/dist/vm/ios/TotalCross.ipa' does not exist

**Comment by brunoamuniz** [comment]
@acmlira fixed both
