### ISSUE TITLE
Failed to execute goal com.totalcross:totalcross-maven-plugin:2.0.2:retrolambda (post-compile)

### ISSUE THREAD

**Issue by nosadaniel** [TotalCross/totalcross#333]
## Describe the bug

Failed to execute goal com.totalcross:totalcross-maven-plugin:2.0.2:retrolambda (post-compile)

## Devices:
Please complete the following information:
 - System OS (name and version): [macOS Big Sur
<img width="1440" alt="Screenshot 2021-04-27 at 15 26 22" src="https://user-images.githubusercontent.com/33612084/116249317-fabe1580-a76c-11eb-89d2-1c0cc885df10.png">
]
 - TotalCross Version: [e.g. 7.0.4]
 - TotalCross backend: [e.g. TotalCross binary or Zulu OpenJDK]
 - Architecture: [e.g. ARM64]
 - Device description: [e.g. Android ]

**Comment by VicMisael** [comment]
It looks like it's not finding the java jre executable,can you check if it's present at the folder that it's trying to find?

**Comment by nosadaniel** [comment]
> It looks like it's not finding the java jre executable,can you check if it's present at the folder that it's trying to find?

It is not present

**Comment by flsobral** [comment]
Hi @nosadaniel, apparently the path for the java executable inside the Zulu JDK 11 changed since the release of the version 2.0.2 of the plugin.

I have just released a new version of the plugin, try updating your pom to use 2.0.3 and it should work.

**Comment by nosadaniel** [comment]
thanks.... is working now
