### ISSUE TITLE
CAUGHT UNHANDLED EXCEPTION IN EVENT THREAD: java.lang.NoSuchMethodError: com.geiger.toolbox.ToolboxUi.lambda$new$0()Ltotalcross/ui/Container;

### ISSUE THREAD

**Issue by nosadaniel** [TotalCross/totalcross#342]
## Describe the bug
A clear and concise description of what the bug is and the actual behavior.

## Devices:
Please complete the following information:
 Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/nosakharedanielahanor/Downloads/apache-maven-3.6.3
Java version: 11.0.10, vendor: Oracle Corporation, runtime: /usr/local/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "11.2.3", arch: "x86_64", family: "mac"
 
 
## To Reproduce
![WhatsApp Image 2021-05-19 at 10 10 53 PM](https://user-images.githubusercontent.com/33612084/118879375-f1017b00-b8f0-11eb-8641-61bd3814bafd.jpeg)

**Comment by brunoamuniz** [comment]
we had this issue sometimes and often just to run a "clean" command it worked back. Could you try to run a "clean package" command and return to me?

**Comment by nosadaniel** [comment]
it works...thanks
