### ISSUE TITLE
how to implement accordion with container that has other element as dropdown

### ISSUE THREAD

**Issue by nosadaniel** [TotalCross/totalcross#346]
I looked at their example on github but they show how to make a kind of input (a multiedit) for the person to type and not a container that has  label and two buttons

## Devices:
Please complete the following information:
 - System OS (name and version): [macOS]
 - TotalCross Version: [e.g. 7.0.7]
 - TotalCross backend: [TotalCross]
 - Architecture: [e.g. ARM64]
 
<img width="1440" alt="Screenshot 2021-05-25 at 12 40 09" src="https://user-images.githubusercontent.com/33612084/119485551-853b6a00-bd57-11eb-9eda-eeb77b4d6d80.png">

## Screenshots or videos
If applicable, add some screenshots and/or videos to help to explain your problem.

**Comment by brunoamuniz** [comment]
hello @nosadaniel 

If you solved the issue by yourself, please post some tips for other users that might be the sabe question =)

Cheers,

**Comment by nosadaniel** [comment]
The following are steps that solved my problem:
1. Initialise an array of any Container you want to add to the AccordionContainer.
  AccordionContainer.Group gr = new AccordionContainer.Group();
  AccordionContainer ac[] = new AccordionContainer[5];
  Label threatDetails[] = new Label[5];  
  Button ban = new Button[5];

2. run a loop to add values to your container objects
3. run a loop to add AccordionContainer (add(ac[])) and add your container items to AccordionContainer 

![20210627014953](https://user-images.githubusercontent.com/33612084/123528729-0d5fb700-d6ea-11eb-877d-cb1232325cd3.png)
