### ISSUE TITLE
[VSCode Plugin] - Not working

### ISSUE THREAD

**Issue by Fabrizio-PRO-TI-2101** [TotalCross/totalcross#347]
Hi, there!

I'm using Ubuntu 20.04 to develop some code and study the new Totalcross features. However, it's not working and I kindly ask your support to help me fix it, please! The detailed steps are illustrated below, and I hope nothing is missing!

1) I installed Java, and Maven, as follows:
![Captura de tela de 2021-05-26 15-09-15](https://user-images.githubusercontent.com/84917810/119837390-eb032f80-bed8-11eb-948f-22e806fad06a.png)

2) The Totalcross plugin is installed in VS Code and Java is configured, as follows:
![Captura de tela de 2021-05-26 15-14-56](https://user-images.githubusercontent.com/84917810/119837751-3fa6aa80-bed9-11eb-8288-a02493ec8061.png)

![Captura de tela de 2021-05-26 15-16-22](https://user-images.githubusercontent.com/84917810/119837866-54833e00-bed9-11eb-99ed-d921e0919fb8.png)

![Captura de tela de 2021-05-26 15-17-06](https://user-images.githubusercontent.com/84917810/119837984-6bc22b80-bed9-11eb-91d8-d4c5ea24b1ae.png)

![Captura de tela de 2021-05-26 15-17-39](https://user-images.githubusercontent.com/84917810/119838418-c6f41e00-bed9-11eb-8878-c664d5daac4a.png)

3) The Totalcross project is being created as follows:
![Captura de tela de 2021-05-26 15-27-35](https://user-images.githubusercontent.com/84917810/119838481-d4110d00-bed9-11eb-82ef-c1fa7b174afe.png)

![Captura de tela de 2021-05-26 15-28-14](https://user-images.githubusercontent.com/84917810/119838547-e0956580-bed9-11eb-9f83-e431f5e849c8.png)

![Captura de tela de 2021-05-26 15-28-45](https://user-images.githubusercontent.com/84917810/119838614-eee38180-bed9-11eb-9076-4f5814c14778.png)

![Captura de tela de 2021-05-26 15-29-13](https://user-images.githubusercontent.com/84917810/119838686-fd319d80-bed9-11eb-9bfa-48e09e8bdd27.png)

4) The following context menu is displayed:  
![Captura de tela de 2021-05-26 15-31-38](https://user-images.githubusercontent.com/84917810/119838781-0d497d00-beda-11eb-9135-f07f29f61e91.png)

5) If I choose Run Java, the following message is displayed (at the right bottom):
![Captura de tela de 2021-05-26 15-32-07](https://user-images.githubusercontent.com/84917810/119838854-1f2b2000-beda-11eb-9cca-a0baacd62a9e.png)

6) If I choose Cancel, nothing happens. If I choose Yes, then...
![Captura de tela de 2021-05-26 15-33-45](https://user-images.githubusercontent.com/84917810/119838925-2ce0a580-beda-11eb-80e0-2c1b741a2c63.png)

![Captura de tela de 2021-05-26 15-34-21](https://user-images.githubusercontent.com/84917810/119839042-3ec24880-beda-11eb-8229-79bbef7793cb.png)

Best regards,
Fabrizio.

**Comment by brunoamuniz** [comment]
Hello @Fabrizio-PRO-TI-2101,

It looks like a java installation issue. Did you try to use a different SDK? We use to recommend Azul Java build. Try this and give us the results 

https://www.azul.com/downloads/#download-openjdk

**Comment by Fabrizio-PRO-TI-2101** [comment]
Hello, @brunoamuniz .

   Well, I think it has worked, as follows! If I need further help, I'll surely let you know!
   
![image](https://user-images.githubusercontent.com/84917810/120201277-a38fe280-c1fb-11eb-90f5-10473af85651.png)


   
   Thanks a lot!

Best regards,
Fabrizio.
