### ISSUE TITLE
[Documentation issue] - QR Code reader

### ISSUE THREAD

**Issue by Fabrizio-PRO-TI-2101** [TotalCross/totalcross#349]
Hi, there!

   I'm studying about QR Code, and taking a look at the QR Code documentation, there might be a broken link, as follows:
   ![image](https://user-images.githubusercontent.com/84917810/120809129-29739c80-c520-11eb-80e5-26ce3fa16d03.png)

   When I click on the link to read the explanation to create a QR Code reader, then it "jumps" to an unexisting page, as follows:
   ![image](https://user-images.githubusercontent.com/84917810/120809481-7bb4bd80-c520-11eb-84e3-5a5b73969534.png)

  Could you please check?

Best regards,
Fabrizio.

**Comment by brunoamuniz** [comment]
Thanks so much!! We just fixed it, here's the link =)

https://learn.totalcross.com/documentation/apis/barcode-scanner
