### ISSUE TITLE
Broken link - CONTRIBUTING.md

### ISSUE THREAD

**Issue by nmarquesin** [TotalCross/totalcross#36]
Link to "term to become a contributor" is broken.

**Comment by VaneskaSousa** [comment]
It's on readme.md or on learn.totalcross.com?

**Comment by nmarquesin** [comment]
It's on CONTRIBUTING.md in this repo https://github.com/TotalCross/totalcross/blob/develop/CONTRIBUTING.md
Please, check line 11 on that file.
