### ISSUE TITLE
Error send request in httpStream

### ISSUE THREAD

**Issue by FelipeRodrigues21** [TotalCross/totalcross#362]
Hello Guys, how are you?
When I will send the request(Verb POST) with body, in my application use httpStream, i receive in my response 415 HTTP code of my API. I did many tests in my API and it is work well. My API accept only json content type and in my app but, continue with with error HTTP code 415.
Error bellow:

"<html><head><title>Error</title></head><body>Unsupported Media Type</body></html>" 

- TotalCross Version: 6.1.0
 
 In my application i will try add string of json in atriibutes data and dataSb of Object options

**Comment by jeffque** [comment]
Could you please write your request here?

Probably just a missing header, but to be sure I need to read the code

**Comment by FelipeRodrigues21** [comment]
@jeffque  i resolved the problem, it using method put of header, previously i was options.setContentType and the method doens' work. I think the error is the method setContentType.

**Comment by FelipeRodrigues21** [comment]
Code bellow work:

Hashtable header = new Hashtable(0);
header.put("Content-Type", "application/json");

Code bellow doens't work:

options.setContentType("application/json");

**Comment by brunoamuniz** [comment]
As the issue is solved, I am going to closed.

Cheers,
