### ISSUE TITLE
Lambda support

### ISSUE THREAD

**Issue by VaneskaSousa** [TotalCross/totalcross#5]
It is essential to use lambda so that I can run embedded applications while consuming as little memory as possible. In addition to avoiding bugs caused by the way TotalCross handles retrolambda / lambda

**Comment by jeffque** [comment]
What bugs in retrolambda?

I use it extensively, and I shall say that the only issues I had with it are:

1. junit tests
2. when on a Maven Reactor, the lambda classes deploys to a random JAR file that may or may not be picked up by `tc-compiler-help` (luontola/retrolambda#156, but I need to get the minimum example up and running and open a new issue about that)

Besides that, no problems.

Also, it would be useful if you let @luontola aware of your issues, preferable opening issues at [luontola/retrolambda](https://github.com/luontola/retrolambda) repo

**Comment by ItaloYeltsin** [comment]
For now I think we should wait the users to open a issue related to this. In the past we had some problems with retrolambda because of the way it was being called in the totalcross-maven-plugin. Currently, users have not complaning about any issues related to retrolambda!
