### ISSUE TITLE
Automate docker builds on the repository

### ISSUE THREAD

**Issue by ItaloYeltsin** [TotalCross/totalcross#52]
This is a really good first issue to do. At the folders `TotalCrossVM/builder/gcc-linux-arm/docker-builder-image` and `TotalCrossVM/builder/gcc-posix/docker-builder-image`

These docker images are made to build vm and launchers at the following build.sh:
`TotalCrossVM/builder/gcc-linux-arm/Launcher/build.sh`
`TotalCrossVM/builder/gcc-linux-arm/tcvm/build.sh`
`TotalCrossVM/builder/gcc-posix/Launcher/build.sh`
`TotalCrossVM/builder/gcc-posix/tcvm/build.sh`

This is a really good and easy way to start contributing to totalcross. I hope someone out of our main team take this!

**Comment by acmlira** [comment]
We must retake and reformulate this idea with the arrival of the new build system #71

**Comment by ItaloYeltsin** [comment]
With the new toolchain provided by @otavio maybe this will be no longer required.

**Comment by acmlira** [comment]
I don't think so, we should still make the Docker option available since the toolchain has the limited scope of compatible systems.
