### ISSUE TITLE
Apply easing curve to Flick animation

### ISSUE THREAD

**Issue by flsobral** [TotalCross/totalcross#58]
I have noticed the Flick implementation is based on the equation for constant translational acceleration in a straight line (MRUV in portuguese), which is repeated at least a couple of times in the Flick implementation.
According to @ItaloYeltsin , we could improve the flick animation by moving this duplicated into a single function and then replace it with some kind of easing curve equation.

This was observed on the Flick class, v6.0.4.

**Comment by acmlira** [comment]
Hey @ItaloYeltsin what the current state about that?

**Comment by ItaloYeltsin** [comment]
@ricardobna can do this!

**Comment by acmlira** [comment]
@ItaloYeltsin worked on this issue and the solution was reverted to the past implementation.
