### ISSUE TITLE
Poor performance on low-end devices

### ISSUE THREAD

**Issue by acmlira** [TotalCross/totalcross#63]
The performance on **low-end** devices is not pleasant, we need to rework the update loop and some parts of the screen/events update code.

### Seen on
- Colibri iMX6ULL
- Beaglebone Black

**Comment by acmlira** [comment]
Few changes are being made to address this issue. In our calendar, we will work on it at the end of 2020 😢

**Comment by flsobral** [comment]
The optimizations made for sdlsurface and opaque images were enough for this particular scenario.

**Comment by acmlira** [comment]
We need to close #127 ?
