### ISSUE TITLE
Trying to run my sample applications at Rasp Zero W and a segfault is showing up

### ISSUE THREAD

**Issue by brunoamuniz** [TotalCross/totalcross#87]
## Describe the bug
I am testing some sample applications on a Rasp Zero W but I segFault is showing up for me

## To Reproduce

Package, deploy and run the application on the device, it is enough to simulate the error

I tried with CoronaChart, HomeAppliance and a brand new sample too, I had the same issue in all of them

## Expected behavior
To run the application properly

## Devices:
Please complete the following information:
 - Device: Raspberry Zero W
 - OS: Linux Raspbian

**Comment by acmlira** [comment]
Today, to run on it you must compile TotalCross for `armv5` inside a Docker or using some toolchain.  I think this is not a bug but a question about distribution: *should we provide TotalCross for this architecture?*. In addition you may encounter problems with Skia which should also be compiled for this architecture.

Stay tuned with the new build system (#71), it will make this job a lot easier 😄
